// Import the jsonwebtoken library
// This library is used to create and verify JSON Web Tokens (JWT)
const jwt = require("jsonwebtoken");

// Initialize dotenv and load all variables form the .env file into 'process.env'
require('dotenv').config();

// JSON Web Tokens
// A JWT is a token used for authentication that proves who you are after login.

// TOKEN CREATION
// Generate JWT Access Token for Authenticated Users
// JWT Anatomy
    // Header (auto-generated by JWT library)
    // Payload (contains user data / claims)
    // Signature (created using the secret key)
module.exports.createAccessToken = (user) => {
    // Create a payload object that contains the user's information
    // These are called "claims" and will be stored inside the token
    const data = {
        id: user._id,
        email: user.email,
        isAdmin: user.isAdmin
    }

    // Generate a JWT using the payload (data), secret key (process.env.JWT_SECRET_KEY), and optional settings
    // jwt.sign() creates the token
        // 1st argument: data (payload)
        // 2nd argument: secret key (used to sign the token securely)
        // 3rd argument: options (empty for now, but can include expiration of token, etc.)
    return jwt.sign(data, process.env.JWT_SECRET_KEY, {});
}

// Middleware to validate and decode JWT from Request Headers
// Parameters
    // req  - contains data from the client (headers, body, params)
    // res  - used to send a response back to the client
    // next - function that passes control to the next middleware or route
module.exports.verify = (req, res, next) => {

    // Log the Authorization header
    // Result: "Bearer <JWT>"
    console.log(req.headers.authorization);

    // Retrieve the authorization header which contains the token
    let token = req.headers.authorization;

    // Check if the token exists
    if (typeof token === "undefined") {
        // If no token is provided, the user is not authorized to access protected routes
        return res.send({auth: "Failed. No Token."})
    // If token exists
    } else {
        // Result: "Bearer <JWT>"
        console.log(token);

        // Remove the "Bearer " prefix (first 7 characters)
        // This extracts only the actual JWT needed for verification
        token = token.slice(7);

        // Result: "<JWT>"
        console.log(token);

        // Verify a JWT using the token, secret key, and a callback function
        // jwt.verify() checks if the token is valid and not tampered
            // 1st argument: token (the JWT from the client, usually from headers)
            // 2nd argument: secret key (must be the same key used in jwt.sign)
            // 3rd argument: function (returns err or decodedToken)
        jwt.verify(token, process.env.JWT_SECRET_KEY, (err, decodedToken) => {
            // If verification fails, an error is returned
            // Possible reasons for error:
                // Invalid token format
                // Token has been altered
                // Worng secret key
                // Token has expired 
            if (err) {
                // status(403) means the client is not allowed to access the resource
                // 403 Forbidden
                return res.status(403).send({
                    auth: "Failed",
                    // err.message is built-in property from the Error object
                    // It contains the reason why verification failed
                    message: err.message
                })
            // If verification success
            } else {

                // If successful, decodedToken contains user data (payload)
                console.log("result from verify method:");
                console.log(decodedToken);

                // Attach decoded user data to request object to allow access in protected routes
                req.user = decodedToken;

                // next() is function that passes control to the next middleware or route handler
                next();

            }
        })
    }

}

// Middleware to check if authenticated is an admin
module.exports.verifyAdmin = (req, res, next) => {
    // req.user contains the decoded token data (added by verify middleware)
    // It includes the isAdmin property
    // Check if the authenticated user has admin privileges
    if (req.user.isAdmin) {
        // If user is an admin, allow access to the next middleware or route handler.
        next();
    } else {
        // If user is not an admin, deny access
        // End the request-response cycle with an error message
        // status(403) means the client is authenticated but not allowed to this resource
        // 403 Forbidden
        return res.status(403).send({
            auth: "Failed",
            message: "Action Forbidden"
        })
    }
}

// Error Handling Middleware
// Instead of handling errors in every route, we centralize error handling using middleware
// This middleware catches error from ANYWHERE in the application.
module.exports.errorHandler = (err, req, res, next) => {

    // Log the error on the server
    console.error(err); 

    // Use 'err.status' if status code is available in the error object, otherwise default to 500 (Internal Server Error)
    const statusCode = err.status || 500;
    // Get the error message
    // err.message - built-in and contains what went wrong
    // If no message is provided in the error object, use 'Internal Server Error'
    // 'Internal Server Error' - generic/default error message
    const errorMessage = err.message || 'Internal Server Error';

    // using res.json() instead of res.send() makes your API responses consistent, especially for errors.
    // res.json() is used to send data to the client in JSON format.
    res.status(statusCode).json({
        // Main error object for consistent API structure
        error: {
            // human-readable error
            message: errorMessage,
            // err.code is used for db errors
            // If not provided by the error object, use 'SERVER ERROR' as default
            errorCode: err.code || 'SERVER ERROR',
            // Additional details
            // If not provided by the error object, use 'null' as default
            details: err.details || null
        }
    })
}

// Middleware used in protected routes to check if the user has been authenticated
// Middleware to check if the user is authenticated/logged in
module.exports.isLoggedIn = (req, res, next) => {
    if (req.user) {
        next();
    } else {
        // res.status(401).send("Unauthorized")
        res.sendStatus(401);
    }
}